### ISSUE TITLE
[PSP] Fix home button

### ISSUE THREAD

**Issue by antim0118** [TheFusionEngine/FusionEngine#9]
Can you use callbacks for home button?

Like I did it here: https://github.com/Homebrodot/Godot/pull/18/commits/d17152150b2eed85c0e5b2a3f5c67704b6ba6784

**Comment by I-asked** [comment]
@antim0118 your code is wrong BTW, but feel free to adopt our implementation, as long as you mention Fusion Engine in the file's header :wink:

**Comment by antim0118** [comment]
> your code is wrong BTW
what's wrong bruh, you can find this code in any psp project.
at least it works.

**Comment by I-asked** [comment]
> what's wrong bruh, you can find this code in any psp project.

It doesn't handle exit gracefully and instead it terminates forcefully.

> at least it works.
Please elaborate. I tested it and it works on my physical PSP-2000.
